language: node_js

node_js:
  - '9'

cache:
  directories:
    - node_modules

script:
  - npm run build
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    cd dist;
    git init;
    git config user.name 'zhuweiyou';
    git config user.email 'i@zhuweiyou.com';
    git add .;
    git commit -m 'auto deploy';
    git push https://${GH_TOKEN}@github.com/fpass/fpass.git master:gh-pages -f;
    fi

branches:
  only:
    - master
    - /^greenkeeper/.*$/
